format = """
$battery\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = " "

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"


[character]
success_symbol = '[λ](bold green)'   # success
error_symbol   = '[⊥](bold red)'     # error / contradiction
vicmd_symbol   = '[∷](bold yellow)' # vim command mode

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_commit]
style = "bright-black"
format = "[$hash]($style)"
length = 7

[git_status]
format = "[ $conflicted $untracked $modified $staged $renamed $deleted]($style) ($ahead_behind $stashed)"
style = "cyan"
conflicted = "CON"   # Conflict
untracked  = "NEW"   # New/untracked files
modified   = "MOD"   # Modified files
staged     = "STG"   # Staged files
renamed    = "REN"   # Renamed files
deleted    = "DEL"   # Deleted files
stashed    = "STS"   # Stashed changes

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
